# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'source/supertool/weather.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 695)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWeather = QtWidgets.QWidget()
        self.tabWeather.setObjectName("tabWeather")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabWeather)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEditAddress = QtWidgets.QLineEdit(self.tabWeather)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditAddress.sizePolicy().hasHeightForWidth())
        self.textEditAddress.setSizePolicy(sizePolicy)
        self.textEditAddress.setMinimumSize(QtCore.QSize(200, 30))
        self.textEditAddress.setMaximumSize(QtCore.QSize(600, 60))
        self.textEditAddress.setBaseSize(QtCore.QSize(725, 100))
        self.textEditAddress.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEditAddress.setText("")
        self.textEditAddress.setDragEnabled(True)
        self.textEditAddress.setObjectName("textEditAddress")
        self.horizontalLayout.addWidget(self.textEditAddress)
        self.weatherButton = QtWidgets.QPushButton(self.tabWeather)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weatherButton.sizePolicy().hasHeightForWidth())
        self.weatherButton.setSizePolicy(sizePolicy)
        self.weatherButton.setMaximumSize(QtCore.QSize(200, 60))
        self.weatherButton.setObjectName("weatherButton")
        self.horizontalLayout.addWidget(self.weatherButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.labelCurrentWeather = QtWidgets.QLabel(self.tabWeather)
        self.labelCurrentWeather.setBaseSize(QtCore.QSize(725, 0))
        self.labelCurrentWeather.setText("")
        self.labelCurrentWeather.setWordWrap(True)
        self.labelCurrentWeather.setObjectName("labelCurrentWeather")
        self.gridLayout.addWidget(self.labelCurrentWeather, 1, 0, 1, 1)
        self.tableWidgetCurrentWeather = QtWidgets.QTableWidget(self.tabWeather)
        self.tableWidgetCurrentWeather.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableWidgetCurrentWeather.sizePolicy().hasHeightForWidth())
        self.tableWidgetCurrentWeather.setSizePolicy(sizePolicy)
        self.tableWidgetCurrentWeather.setMinimumSize(QtCore.QSize(739, 56))
        self.tableWidgetCurrentWeather.setMaximumSize(QtCore.QSize(16777215, 56))
        self.tableWidgetCurrentWeather.setBaseSize(QtCore.QSize(739, 56))
        self.tableWidgetCurrentWeather.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetCurrentWeather.setAlternatingRowColors(False)
        self.tableWidgetCurrentWeather.setObjectName("tableWidgetCurrentWeather")
        self.tableWidgetCurrentWeather.setColumnCount(5)
        self.tableWidgetCurrentWeather.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrentWeather.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrentWeather.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrentWeather.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrentWeather.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrentWeather.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCurrentWeather.setHorizontalHeaderItem(4, item)
        self.tableWidgetCurrentWeather.horizontalHeader().setDefaultSectionSize(155)
        self.tableWidgetCurrentWeather.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetCurrentWeather.verticalHeader().setVisible(False)
        self.tableWidgetCurrentWeather.verticalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidgetCurrentWeather, 2, 0, 1, 1)
        self.labelForecastWeather = QtWidgets.QLabel(self.tabWeather)
        self.labelForecastWeather.setEnabled(True)
        self.labelForecastWeather.setBaseSize(QtCore.QSize(725, 0))
        self.labelForecastWeather.setText("")
        self.labelForecastWeather.setWordWrap(True)
        self.labelForecastWeather.setObjectName("labelForecastWeather")
        self.gridLayout.addWidget(self.labelForecastWeather, 3, 0, 1, 1)
        self.tableWidgetForecastWeather = QtWidgets.QTableWidget(self.tabWeather)
        self.tableWidgetForecastWeather.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tableWidgetForecastWeather.sizePolicy().hasHeightForWidth())
        self.tableWidgetForecastWeather.setSizePolicy(sizePolicy)
        self.tableWidgetForecastWeather.setMinimumSize(QtCore.QSize(780, 181))
        self.tableWidgetForecastWeather.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetForecastWeather.setDragDropOverwriteMode(False)
        self.tableWidgetForecastWeather.setAlternatingRowColors(True)
        self.tableWidgetForecastWeather.setObjectName("tableWidgetForecastWeather")
        self.tableWidgetForecastWeather.setColumnCount(6)
        self.tableWidgetForecastWeather.setRowCount(40)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(32, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(33, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(34, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(35, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(36, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(37, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(38, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setVerticalHeaderItem(39, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForecastWeather.setHorizontalHeaderItem(5, item)
        self.tableWidgetForecastWeather.horizontalHeader().setDefaultSectionSize(127)
        self.tableWidgetForecastWeather.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetForecastWeather.verticalHeader().setVisible(False)
        self.tableWidgetForecastWeather.verticalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidgetForecastWeather, 4, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabWeather, "")
        self.tabSimilar = QtWidgets.QWidget()
        self.tabSimilar.setObjectName("tabSimilar")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabSimilar)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditSimilar = QtWidgets.QLineEdit(self.tabSimilar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEditSimilar.sizePolicy().hasHeightForWidth())
        self.lineEditSimilar.setSizePolicy(sizePolicy)
        self.lineEditSimilar.setMinimumSize(QtCore.QSize(500, 30))
        self.lineEditSimilar.setMaximumSize(QtCore.QSize(1000, 60))
        self.lineEditSimilar.setBaseSize(QtCore.QSize(500, 30))
        self.lineEditSimilar.setText("")
        self.lineEditSimilar.setObjectName("lineEditSimilar")
        self.horizontalLayout_2.addWidget(self.lineEditSimilar)
        self.similarButton = QtWidgets.QPushButton(self.tabSimilar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.similarButton.sizePolicy().hasHeightForWidth())
        self.similarButton.setSizePolicy(sizePolicy)
        self.similarButton.setMinimumSize(QtCore.QSize(130, 30))
        self.similarButton.setMaximumSize(QtCore.QSize(200, 60))
        self.similarButton.setBaseSize(QtCore.QSize(130, 30))
        self.similarButton.setObjectName("similarButton")
        self.horizontalLayout_2.addWidget(self.similarButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textBrowser = QtWidgets.QTextBrowser(self.tabSimilar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(500, 50))
        self.textBrowser.setBaseSize(QtCore.QSize(500, 50))
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabSimilar, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionChange = QtWidgets.QAction(MainWindow)
        self.actionChange.setObjectName("actionChange")
        self.actionSimilar = QtWidgets.QAction(MainWindow)
        self.actionSimilar.setObjectName("actionSimilar")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEditAddress.setPlaceholderText(_translate("MainWindow", "Enter address"))
        self.weatherButton.setText(_translate("MainWindow", "Search"))
        item = self.tableWidgetCurrentWeather.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetCurrentWeather.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidgetCurrentWeather.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Humidity, %"))
        item = self.tableWidgetCurrentWeather.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Pressure.,mm Hg"))
        item = self.tableWidgetCurrentWeather.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Temp, °C"))
        item = self.tableWidgetCurrentWeather.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Wind"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(16)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(17)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(18)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(19)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(20)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(21)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(22)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(23)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(24)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(25)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(26)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(27)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(28)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(29)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(30)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(31)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(32)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(33)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(34)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(35)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(36)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(37)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(38)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.verticalHeaderItem(39)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetForecastWeather.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidgetForecastWeather.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidgetForecastWeather.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Humidity, %"))
        item = self.tableWidgetForecastWeather.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Pressure.,mm Hg"))
        item = self.tableWidgetForecastWeather.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Temp, °C"))
        item = self.tableWidgetForecastWeather.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Wind"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWeather), _translate("MainWindow", "Weather"))
        self.lineEditSimilar.setPlaceholderText(_translate("MainWindow", "Enter directory"))
        self.similarButton.setText(_translate("MainWindow", "Find similar files"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSimilar), _translate("MainWindow", "Similar"))
        self.actionChange.setText(_translate("MainWindow", "Weather"))
        self.actionSimilar.setText(_translate("MainWindow", "Similar"))

